# This workflow will install Python dependencies then run the script

name: Check available dates

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install poetry==1.0.0
        poetry install
    - name: Run main.py to check availability
      id: checkAvailability
      run: |
        poetry run python main.py
    - name: Send SMS notification 1
      if: steps.checkAvailability.outcome == 'failure'
      uses: twilio-labs/actions-sms@v1
      with:
        fromPhoneNumber: ${{ secrets.TWILIO_FROM_NUMBER }}
        toPhoneNumber: ${{ secrets.TWILIO_TO_NUMBER_1 }}
        message: 'New MIQ dates may be available'
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
        TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
